version: '3.8'
services:
  dealer:
    build: ./dealer
    container_name: dealer_c
    ports:
      - 8000:8000
    volumes:
      - ./dealer:/app
      - ./app/node_modules
  card_game:
    build: ./cardgame
    container_name: card_game_c
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - ./cardgame:/app
      - ./app/node_modules